-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 16:52:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AED_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AED_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AED_db` DEFAULT CHARACTER SET utf8 ;
USE `AED_db` ;

-- -----------------------------------------------------
-- Table `AED_db`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AED_db`.`Materias` (
  `idMaterias` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `faltas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AED_db`.`compromissos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AED_db`.`compromissos` (
  `idcompromissos` INT NOT NULL AUTO_INCREMENT,
  `descrição` VARCHAR(255) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idcompromissos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AED_db`.`Provas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AED_db`.`Provas` (
  `ProvasID` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  PRIMARY KEY (`ProvasID`),
  CONSTRAINT `Materias`
    FOREIGN KEY (`ProvasID`)
    REFERENCES `AED_db`.`Materias` (`idMaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `AED_db`;

DELIMITER $$
USE `AED_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `AED_db`.`Provas_AFTER_INSERT` AFTER INSERT ON `Provas` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
